version: "3"

services:

    master:
        image: danny4927/docker-spark-master
        command: bin/spark-class org.apache.spark.deploy.master.Master -h master
        hostname: master
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.type == spark-master
        environment:
            MASTER: spark://master:7077
        ports:
            - 6066:6066
            - 7077:7077
            - 8080:8080
    worker:
        image: danny4927/docker-spark-worker
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
        hostname: worker 
        deploy:
            replicas: 2
            placement:
                constraints: 
                    - node.labels.type == spark-worker
        environment:
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
