version: "3"

services:

    master:
        image: sauloricci/docker-spark-master
        command: bin/spark-class org.apache.spark.deploy.master.Master -h master
        hostname: master
        deploy:
            mode: global
            placement:
                constraints:
                    - node.hostname == docker-master
        environment:
            MASTER: spark://master:7077
            SPARK_PUBLIC_DNS: $EXTERNAL_IP
        expose:
            - 7001
            - 7002
            - 7003
            - 7004
            - 7005
            - 7006
            - 7077
            - 6066
            - 8080
            - 4040
        ports:
           - 666:666
           - 667:667
           - 4040:4040
           - 4041:4041
           - 6066:6066
           - 7077:7077
           - 8080:8080
    worker:
        image: sauloricci/docker-spark-worker
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
        hostname: worker
        deploy:
            mode: global
            placement:
                constraints: 
                    - node.hostname == docker-worker
        environment:
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
            SPARK_PUBLIC_DNS: $EXTERNAL_IP
        links:
            - master
        expose:
            - 7012
            - 7013
            - 7014
            - 7015
            - 7016
            - 8881
