version: "3"

services:

    master:
        image: danny4927/docker-spark-master
        command: bin/spark-class org.apache.spark.deploy.master.Master -h master
        hostname: master
        deploy:
            mode: global
            placement:
                constraints:
                    - node.labels.type == spark-master
        environment:
            MASTER: spark://master:7077
        ports:
            - 666:666
            - 667:667
            - 4040:4040
            - 4041:4041
            - 6066:6066
            - 7077:7077
            - 7001:7001
            - 7002:7002
            - 7003:7003
            - 7004:7004
            - 7005:7005
            - 7006:7006
            - 8080:8080
    worker:
        image: danny4927/docker-spark-worker
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
        hostname: worker 
        deploy:
            mode: global
            placement:
                constraints: 
                    - node.labels.type == spark-worker
        environment:
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
        ports:
            - 7012:7012
            - 7013:7013
            - 7014:7014
            - 7015:7015
            - 7016:7015
            - 8081:8081
            - 8881:8881
