version: "3"

services:

    master:
        image: sauloricci/docker-spark-master
        command: bin/spark-class org.apache.spark.deploy.master.Master -h master
        hostname: master
        deploy:
            mode: global
            placement:
                constraints: [node.labels.type == master]
        environment:
            MASTER: spark://master:7077
            SPARK_PUBLIC_DNS: $EXTERNAL_IP
        expose:
            - 7001
            - 7002
            - 7003
            - 7004
            - 7005
            - 7006
            - 7077
            - 6066
        volumes:
            - /mnt/spark_data:/data
            - /data1:/data1
            - /data2:/data2
            - /data3:/data3
            - /data4:/data4

    worker:
        image: sauloricci/docker-spark-worker
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
        hostname: worker
        deploy:
            mode: global
            placement:
                constraints: [node.labels.type == worker]
        environment:
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
            SPARK_PUBLIC_DNS: $EXTERNAL_IP
        links:
            - master
        expose:
            - 7012
            - 7013
            - 7014
            - 7015
            - 7016
            - 8881
        volumes:
            - /data1:/data1
            - /data2:/data2
            - /data3:/data3
            - /data4:/data4

    notebook:
        image: sauloricci/notebook
        command: start-notebook.sh --NotebookApp.token=''
        hostname: notebook
        deploy:
            placement:
                constraints: [node.labels.type == master]
        environment:
            TINI_SUBREAPER: "true"
            GRANT_SUDO: "yes"
            SPARK_PUBLIC_DNS: $EXTERNAL_IP
        links:
            - master
        pid: "host"
        volumes:
            - /notebook:/home/jovyan/work
    
    proxy:
       image: sauloricci/docker_spark_proxy
       hostname: proxy
       deploy:
           placement:
               constraints: [node.labels.type == master]
       links:
           - master
       ports:
           - 666:666 
